#frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clover-stock
  namespace: default
spec:
    replicas: 3
    selector:
      matchLabels:
        app: clover-stock
    template:
      metadata:
        labels:
          app: clover-stock
      spec:
        containers:
          - name: clover-stock
            image: AWS_ECR_URI
            imagePullPolicy: Always
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: 10m
              limits:
                cpu: 50m
            
            
