apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-frontend
  namespace: default
spec:
    replicas: 3
    selector:
      matchLabels:
        app: demo-frontend
    template:
      metadata:
        labels:
          app: demo-frontend
      spec:
        containers:
          - name: demo-frontend
            image: 602401143452.dkr.ecr.ap-northeast-2.amazonaws.com/$IMAGE_REPO_NAME:68e10666
            imagePullPolicy: Always
            ports:
              - containerPort: 80
